variable "bucket" {}
variable "SANDBOX_ID" {}
variable "item1" {}
variable "item2" {}
variable "item3" {}
variable "PUBLIC_ADDRESS" {}
variable "AWS_ACCESS_KEY_ID" {}
variable "AWS_SECRET_ACCESS_KEY" {}
variable "AWS_DEFAULT_REGION" {}
